[book]
authors = ["orb li"]
language = "en"
multilingual = false
src = "src"
title = "sovon limited - eep capital"

[build]
build-dir = "docs"

[output.html]
mathjax-support = true
default-theme = "navy"
git-repository-url = "https://github.com/sovon-l/document"